target-version = "py314"

line-length = 120

[lint]
extend-select = [
    "UP", # pyupgrade
    "B",
    "I",
    "E501",
]

ignore = [
    "B008",
    "B024",
    "F401",
    "B904",
    "F841",
    "F821", # временно, пока тесты не исправятся
]

# Disable fix for unused imports (`F401`).
# отменяет удаление неиспользуемых импортов
unfixable = ["F401"]
